monitor.alsa.rules = [
    {
        matches = [
            # Match any USB sound card or USB headphones
            node.name = "~alsa_output.usb-.*"
        ]
        actions = {
            update-props = {
                # Force higher priority than internal audio (default is 1000)
                priority.driver = 2000
                priority.session = 2000
            }
        }
    }
]
