#!/bin/bash

sleep 0.25
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
logger 'killed all xdg-desktop'

sleep 0.25
/usr/libexec/xdg-desktop-portal-hyprland &
logger 'xdg-desktop-portal-hyprland started'
sleep 0.5
/usr/libexec/xdg-desktop-portal &
logger 'xdg-desktop-portal started'
