program_options:
  tray: false
  notify: true
  automount: false
device_config:
  # Don't auto-mount Tlenix USB
  - id_uuid: 2fab66b0-fd1e-4a8d-b22b-943cb8769e74
    ignore: false
    automount: false
