require("maxgmr.startup")
require("maxgmr.options")
require("maxgmr.plugins")
require("maxgmr.autocmds")

require("maxgmr.colourscheme")
require("maxgmr.colourswap")
require("maxgmr.cmpim")
require("maxgmr.cmp")
require("maxgmr.lsp")
require("maxgmr.conform")
require("maxgmr.crates")
require("maxgmr.telescope")
require("maxgmr.treesitter")
require("maxgmr.autopairs")
require("maxgmr.comment")
require("maxgmr.nvimtree")
require("maxgmr.cokeline")
require("maxgmr.toggleterm")
--[[ require("maxgmr.alpha") ]]
require("maxgmr.lualine")
require("maxgmr.gitsigns")
require("maxgmr.unicodepicker")
require("maxgmr.neorg")

require("maxgmr.keymaps")
